name: Analyze with CodeGuru Reviewer

# on: 
#  - push
#  - workflow_dispatch # This allows manual triggering of the action through the GitHub UI.

on: 
  pull_request:
    types: [opened,reopened]
  

permissions:
    id-token: write
    # required for all workflows
    security-events: write

    # only required for workflows in private repositories
    actions: read
    contents: read

jobs:
  build:
    name: Analyze with CodeGuru Reviewer
    runs-on: ubuntu-latest
    steps:     
    - name: Configure AWS credentials
      id: iam-role
      continue-on-error: false
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::632161794143:role/OIDCgithub-Role
        aws-region: us-west-2
    
    - uses: actions/checkout@v2
      if: steps.iam-role.outcome == 'success'
      with:
        fetch-depth: 0
    - name: Set up JDK 1.8
      if: steps.iam-role.outcome == 'success'
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build project
      if: steps.iam-role.outcome == 'success'
      run: mvn compile -DskipTests

    - name: CodeGuru Reviewer
      uses: aws-actions/codeguru-reviewer@v1.1
      if: steps.iam-role.outcome == 'success'
      continue-on-error: false
      with:          
        s3_bucket: codeguru-reviewer-githubactions-awsbin
        build_path: ./target/classes
          
#     - name: Upload review result
#       uses: github/codeql-action/upload-sarif@v2
#       with:
#         sarif_file: codeguru-results.sarif.json
        
    - name: Rename file 
      if: steps.iam-role.outcome == 'success'
      run: |
          mv codeguru-results.sarif.json codeguru-results.sarif
          rm -f codeguru-results.sarif.json  
    - name: Publish to comments
      if: steps.iam-role.outcome == 'success'
      shell: bash  
      env:
        MY_TOKEN: ${{ secrets.MY_TOKEN }}
        PR_NUMBER: ${{ github.event.number }}
      run: |
          npm install @security-alert/sarif-to-comment    
          url="https://github.com/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
          GITHUB_TOKEN=$MY_TOKEN npx @security-alert/sarif-to-comment --commentUrl "$url" --sarifContentOwner "${{github.repository_owner}}" --sarifContentRepo "${{ github.event.repository.name }}" --sarifContentBranch "${{ github.sha }}"  "./codeguru-results.sarif"
